--
-- PostgreSQL database dump
--

\restrict TbQWBHKTN30elsDU4gXZO1Ceam8jBpn7obe85otpSOpKlpnOWoqn4ezwfDKCKAA

-- Dumped from database version 16.15 (Ubuntu 16.15-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.15 (Ubuntu 16.15-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: backup_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.backup_logs (
    id integer NOT NULL,
    filename character varying(255) NOT NULL,
    file_path character varying(500) NOT NULL,
    size_bytes bigint,
    created_by integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: backup_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.backup_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.backup_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: business_owners; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.business_owners (
    business_id integer NOT NULL,
    business_name character varying(100) NOT NULL,
    owner_name character varying(100) NOT NULL,
    phone_number character varying(15) NOT NULL,
    email character varying(100),
    password_hash character varying(255) NOT NULL,
    address character varying(150) NOT NULL,
    business_type character varying(100) NOT NULL,
    kebele character varying(50) NOT NULL,
    kifle_ketema character varying(100) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_active boolean DEFAULT true NOT NULL
);


--
-- Name: business_owners_business_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.business_owners ALTER COLUMN business_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.business_owners_business_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: collectors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.collectors (
    id integer NOT NULL,
    full_name character varying(100) NOT NULL,
    phone_number character varying(15) NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    kifle_ketema character varying(100) NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_by integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: collectors_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.collectors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.collectors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: feedback; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.feedback (
    id integer NOT NULL,
    submitter_role character varying(30) NOT NULL,
    submitter_id integer NOT NULL,
    rating integer NOT NULL,
    comment text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT feedback_rating_check CHECK (((rating >= 1) AND (rating <= 5)))
);


--
-- Name: feedback_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.feedback ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.feedback_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: municipal_admins; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.municipal_admins (
    id integer NOT NULL,
    username character varying(100) NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    kifle_ketema character varying(100)
);


--
-- Name: municipal_admins_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.municipal_admins_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: municipal_admins_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.municipal_admins_id_seq OWNED BY public.municipal_admins.id;


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    id integer NOT NULL,
    recipient_role character varying(30) NOT NULL,
    recipient_id integer NOT NULL,
    title character varying(200) NOT NULL,
    message text NOT NULL,
    type character varying(50) NOT NULL,
    is_read boolean DEFAULT false NOT NULL,
    created_by integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: on_demand_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.on_demand_requests (
    id integer NOT NULL,
    business_id integer NOT NULL,
    latitude numeric(10,8) NOT NULL,
    longitude numeric(11,8) NOT NULL,
    description text,
    status character varying(20) DEFAULT 'pending'::character varying NOT NULL,
    admin_notes text,
    reviewed_by integer,
    reviewed_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    collector_id integer,
    collection_status character varying(20) DEFAULT 'unassigned'::character varying,
    assigned_at timestamp without time zone,
    completed_at timestamp without time zone,
    collector_notes text,
    confirmed_at timestamp without time zone
);


--
-- Name: on_demand_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.on_demand_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.on_demand_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: operational_reports; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.operational_reports (
    id integer NOT NULL,
    report_type character varying(30) NOT NULL,
    title character varying(200) NOT NULL,
    date_from date,
    date_to date,
    kifle_ketema character varying(100),
    report_data jsonb NOT NULL,
    generated_by integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: operational_reports_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.operational_reports ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.operational_reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: report_status_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.report_status_history (
    id integer NOT NULL,
    report_id integer NOT NULL,
    old_status character varying(20) NOT NULL,
    new_status character varying(20) NOT NULL,
    changed_by integer NOT NULL,
    changed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: report_status_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.report_status_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.report_status_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reports; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reports (
    id integer NOT NULL,
    resident_id integer NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    status character varying(20) DEFAULT 'pending'::character varying NOT NULL
);


--
-- Name: reports_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.reports_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: reports_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.reports_id_seq OWNED BY public.reports.id;


--
-- Name: residents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.residents (
    id integer NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(100) NOT NULL,
    phone_number character varying(20) NOT NULL,
    kifle_ketema character varying(100) NOT NULL,
    kebele character varying(100) NOT NULL,
    sefer character varying(100) NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    is_active boolean DEFAULT true NOT NULL
);


--
-- Name: residents_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.residents_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: residents_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.residents_id_seq OWNED BY public.residents.id;


--
-- Name: schedule_issue; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schedule_issue (
);


--
-- Name: schedule_issues; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schedule_issues (
    id integer NOT NULL,
    schedule_id integer NOT NULL,
    resident_id integer NOT NULL,
    description text NOT NULL,
    status character varying(20) DEFAULT 'pending'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: schedule_issues_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.schedule_issues_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: schedule_issues_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.schedule_issues_id_seq OWNED BY public.schedule_issues.id;


--
-- Name: schedules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schedules (
    id integer NOT NULL,
    kifle_ketema character varying(100) NOT NULL,
    kebele character varying(100) NOT NULL,
    sefer character varying(100) NOT NULL,
    collection_time time without time zone NOT NULL,
    notes text,
    created_by integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    collector_id integer,
    status character varying(20) DEFAULT 'scheduled'::character varying NOT NULL,
    collection_date date NOT NULL
);


--
-- Name: schedules_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.schedules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schedules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: system_admins; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.system_admins (
    id integer NOT NULL,
    username character varying(100) NOT NULL,
    email character varying(100) NOT NULL,
    password character varying(255) NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: system_admins_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.system_admins ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.system_admins_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: municipal_admins id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.municipal_admins ALTER COLUMN id SET DEFAULT nextval('public.municipal_admins_id_seq'::regclass);


--
-- Name: reports id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reports ALTER COLUMN id SET DEFAULT nextval('public.reports_id_seq'::regclass);


--
-- Name: residents id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.residents ALTER COLUMN id SET DEFAULT nextval('public.residents_id_seq'::regclass);


--
-- Name: schedule_issues id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_issues ALTER COLUMN id SET DEFAULT nextval('public.schedule_issues_id_seq'::regclass);


--
-- Data for Name: backup_logs; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.backup_logs (id, filename, file_path, size_bytes, created_by, created_at) FROM stdin;
\.


--
-- Data for Name: business_owners; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.business_owners (business_id, business_name, owner_name, phone_number, email, password_hash, address, business_type, kebele, kifle_ketema, created_at, is_active) FROM stdin;
1	first	nameOne	0909900909	buso1@gmail.com	$2b$10$Qht8pT43m51ZMugsXzCIseAmJQYkaQvfKPOd4bhJaIL3WbmKFf4fG	debre markose	Hotel	01	abema	2026-09-01 10:24:21.204615	t
\.


--
-- Data for Name: collectors; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.collectors (id, full_name, phone_number, email, password_hash, kifle_ketema, is_active, created_by, created_at) FROM stdin;
\.


--
-- Data for Name: feedback; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.feedback (id, submitter_role, submitter_id, rating, comment, created_at) FROM stdin;
1	resident	9	1	hello	2026-09-01 12:42:25.825368
\.


--
-- Data for Name: municipal_admins; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.municipal_admins (id, username, email, password, created_at, kifle_ketema) FROM stdin;
1	municipaladmin	admin@example.com	$2b$10$iTiQBEc41Ni1dKeTMq1cs.uc/HjVL/0cpocYbZODgR.7n2zH7m4E2	2026-07-29 11:04:24.984729	\N
\.


--
-- Data for Name: notifications; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.notifications (id, recipient_role, recipient_id, title, message, type, is_read, created_by, created_at) FROM stdin;
1	resident	7	this is first repo	notification	manual	f	1	2026-09-01 11:57:22.806084
2	resident	5	this is first repo	notification	manual	f	1	2026-09-01 11:57:22.806084
3	resident	8	this is first repo	notification	manual	f	1	2026-09-01 11:57:22.806084
4	resident	9	this is first repo	notification	manual	f	1	2026-09-01 11:57:22.806084
5	resident	12	this is first repo	notification	manual	f	1	2026-09-01 11:57:22.806084
6	resident	13	this is first repo	notification	manual	f	1	2026-09-01 11:57:22.806084
\.


--
-- Data for Name: on_demand_requests; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.on_demand_requests (id, business_id, latitude, longitude, description, status, admin_notes, reviewed_by, reviewed_at, created_at, collector_id, collection_status, assigned_at, completed_at, collector_notes, confirmed_at) FROM stdin;
1	1	10.25141136	37.74936676	\N	approved	\N	1	2026-09-01 11:48:01.348633	2026-09-01 11:47:08.388421	\N	unassigned	\N	\N	\N	\N
\.


--
-- Data for Name: operational_reports; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.operational_reports (id, report_type, title, date_from, date_to, kifle_ketema, report_data, generated_by, created_at) FROM stdin;
1	schedules	Schedules Report (all time)	\N	\N	\N	{"rows": [{"id": 2, "sefer": "02", "kebele": "03", "status": "scheduled", "kifle_ketema": "abema", "collector_name": null, "collection_date": "2026-08-31T21:00:00.000Z", "collection_time": "14:30:00"}, {"id": 1, "sefer": "01", "kebele": "03", "status": "scheduled", "kifle_ketema": "abema", "collector_name": null, "collection_date": "2026-08-31T21:00:00.000Z", "collection_time": "14:30:00"}, {"id": 5, "sefer": "03", "kebele": "04", "status": "scheduled", "kifle_ketema": "abema", "collector_name": null, "collection_date": "2026-08-31T21:00:00.000Z", "collection_time": "09:00:00"}], "byArea": [{"count": 2, "kebele": "03", "kifle_ketema": "abema"}, {"count": 1, "kebele": "04", "kifle_ketema": "abema"}], "summary": {"total": 3, "assigned": 0, "completed": 0, "scheduled": 3, "in_progress": 0}, "byStatus": [{"count": 3, "status": "scheduled"}]}	1	2026-09-01 12:55:10.837279
\.


--
-- Data for Name: report_status_history; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.report_status_history (id, report_id, old_status, new_status, changed_by, changed_at) FROM stdin;
1	4	pending	in_progress	1	2026-08-29 17:22:07.442517
2	4	in_progress	resolved	1	2026-08-29 17:22:15.350645
3	4	resolved	pending	1	2026-08-29 17:22:21.60087
4	4	pending	in_progress	1	2026-08-29 17:22:25.413914
5	4	in_progress	resolved	1	2026-08-31 11:03:10.763567
6	5	pending	in_progress	1	2026-08-31 15:11:03.370815
7	5	in_progress	pending	1	2026-08-31 15:11:31.702234
\.


--
-- Data for Name: reports; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.reports (id, resident_id, title, description, created_at, status) FROM stdin;
2	5	testing reports 	 this is the test from user  5	2026-07-29 09:49:05.324041	pending
1	5	first report	this is for test reporting from user 5	2026-07-29 09:42:34.714469	in_progress
3	5	Overflowing garbage collection point	The garbage collection area near the main road has been overflowing for several days and needs to be cleaned.	2026-07-29 13:06:42.854152	in_progress
4	8	this is first repo	the first report from user test after getting the crush os\n	2026-08-29 17:19:12.88536	resolved
7	9	Other - Monday	Related collection schedule:\n- Sub-city: abema\n- Kebele: 03\n- Sefer: 02\n- Day: Monday\n- Time: 2:30 PM\n- Schedule notes: this is last collection\n\nIssue reported:\nthat was nice	2026-08-31 11:32:05.59145	pending
8	9	Collection was missed - Monday	Related collection schedule:\n- Sub-city: abema\n- Kebele: 0\n- Sefer: 01\n- Day: Monday\n- Time: 2:30 PM\n- Schedule notes: u should put your garbage from the outside \n\nIssue reported:\nThe scheduled waste collection did not happen as planned.	2026-08-31 14:08:01.25872	pending
9	9	Overflowing or uncollected waste remains - Monday	Related collection schedule:\n- Sub-city: abema\n- Kebele: 03\n- Sefer: 02\n- Day: Monday\n- Time: 2:30 PM\n- Schedule notes: this is last collection\n\nIssue reported:\nWaste is still overflowing or left behind after collection.	2026-08-31 14:14:01.4625	pending
5	9	this is first repo from test2	as the title said it this is the test from me 	2026-08-31 10:35:07.371311	pending
11	9	hello	new report \n	2026-09-01 09:35:35.128618	pending
\.


--
-- Data for Name: residents; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.residents (id, first_name, last_name, email, password_hash, phone_number, kifle_ketema, kebele, sefer, created_at, is_active) FROM stdin;
7	Abe	Kebede	test1@test.com	$2b$10$vJRA9nrnPDNovNmERcklVuTIwLWPeMld/5HrY/YwEW5k4HyF1SjgG	0912345678	Bole	01	01	2026-07-28 10:43:15.908327	t
5	newlyUpdated	secondName	abebe@test.com	$2b$10$1yVmaINKkLT3WnRZDegXJ.qnc57XoU3ZslkH4MBOD5414ZowaCcbi	0912345689	Bole	02	03	2026-07-28 10:40:36.387856	t
8	test	lasname	test1@gmail.com	$2b$10$/rQ5/bM9qPqYpFFjl4GwG.I6hUYRWhwDtYMTRc7XHxTbKC6iugtKy	0909090909	abema	03	04	2026-08-29 17:18:07.004935	t
9	test2	secondN	test2@gmail.com	$2b$10$7MV7O8028P1jAxmdnxvACuN.6gYl0bS4ZhChdmFeNAnfy/xQisZFG	0909900990	abema	03	01	2026-08-31 10:31:13.490576	t
12	Status	Viewer	status-view-1788177513189@test.local	$2b$10$pqEGWlyPuYbuH4xmjiqxB./ZDO8uSIxsgYSdBwuXjeeBClNwrzXI6	0911223344	StatusView	77	66	2026-08-31 14:58:33.325474	t
13	Delete	Tester	delete-report-1788177976127@test.local	$2b$10$DXTFDH8lNwNN1sYE76aoN.HdHNC8TjgKQ1rejsOoSLJD6w7C8r2l.	0911223344	Bole	01	01	2026-08-31 15:06:16.361229	t
\.


--
-- Data for Name: schedule_issue; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.schedule_issue  FROM stdin;
\.


--
-- Data for Name: schedule_issues; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.schedule_issues (id, schedule_id, resident_id, description, status, created_at) FROM stdin;
4	5	12	Collection did not arrive on schedule.	resolved	2026-08-31 14:58:33.480526
3	1	9	Only part of the waste was collected during the scheduled pickup.	resolved	2026-08-31 14:51:43.299653
\.


--
-- Data for Name: schedules; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.schedules (id, kifle_ketema, kebele, sefer, collection_time, notes, created_by, created_at, collector_id, status, collection_date) FROM stdin;
2	abema	03	02	14:30:00	this is last collection	1	2026-08-31 11:17:23.363527	\N	scheduled	2026-09-01
1	abema	03	01	14:30:00	u should put your garbage from the outside 	1	2026-08-31 11:15:26.560053	\N	scheduled	2026-09-01
5	abema	04	03	09:00:00		1	2026-08-31 14:58:33.172844	\N	scheduled	2026-09-01
\.


--
-- Data for Name: system_admins; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.system_admins (id, username, email, password, is_active, created_at) FROM stdin;
1	sysadmin	sysadmin@example.com	$2b$10$lWZIi1zO3eufsBZ2uIRvl.INFewzeHwdD1Z5ftC7aCVVejIuGElIe	t	2026-09-01 13:05:29.458622
\.


--
-- Name: backup_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.backup_logs_id_seq', 1, false);


--
-- Name: business_owners_business_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.business_owners_business_id_seq', 1, true);


--
-- Name: collectors_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.collectors_id_seq', 1, false);


--
-- Name: feedback_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.feedback_id_seq', 1, true);


--
-- Name: municipal_admins_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.municipal_admins_id_seq', 1, true);


--
-- Name: notifications_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.notifications_id_seq', 33, true);


--
-- Name: on_demand_requests_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.on_demand_requests_id_seq', 1, true);


--
-- Name: operational_reports_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.operational_reports_id_seq', 1, true);


--
-- Name: report_status_history_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.report_status_history_id_seq', 7, true);


--
-- Name: reports_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.reports_id_seq', 11, true);


--
-- Name: residents_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.residents_id_seq', 13, true);


--
-- Name: schedule_issues_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.schedule_issues_id_seq', 4, true);


--
-- Name: schedules_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.schedules_id_seq', 5, true);


--
-- Name: system_admins_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.system_admins_id_seq', 1, true);


--
-- Name: backup_logs backup_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.backup_logs
    ADD CONSTRAINT backup_logs_pkey PRIMARY KEY (id);


--
-- Name: business_owners business_owners_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_owners
    ADD CONSTRAINT business_owners_email_key UNIQUE (email);


--
-- Name: business_owners business_owners_phone_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_owners
    ADD CONSTRAINT business_owners_phone_number_key UNIQUE (phone_number);


--
-- Name: business_owners business_owners_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_owners
    ADD CONSTRAINT business_owners_pkey PRIMARY KEY (business_id);


--
-- Name: collectors collectors_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collectors
    ADD CONSTRAINT collectors_email_key UNIQUE (email);


--
-- Name: collectors collectors_phone_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collectors
    ADD CONSTRAINT collectors_phone_number_key UNIQUE (phone_number);


--
-- Name: collectors collectors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collectors
    ADD CONSTRAINT collectors_pkey PRIMARY KEY (id);


--
-- Name: feedback feedback_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feedback
    ADD CONSTRAINT feedback_pkey PRIMARY KEY (id);


--
-- Name: municipal_admins municipal_admins_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.municipal_admins
    ADD CONSTRAINT municipal_admins_email_key UNIQUE (email);


--
-- Name: municipal_admins municipal_admins_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.municipal_admins
    ADD CONSTRAINT municipal_admins_pkey PRIMARY KEY (id);


--
-- Name: municipal_admins municipal_admins_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.municipal_admins
    ADD CONSTRAINT municipal_admins_username_key UNIQUE (username);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: on_demand_requests on_demand_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.on_demand_requests
    ADD CONSTRAINT on_demand_requests_pkey PRIMARY KEY (id);


--
-- Name: operational_reports operational_reports_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.operational_reports
    ADD CONSTRAINT operational_reports_pkey PRIMARY KEY (id);


--
-- Name: report_status_history report_status_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report_status_history
    ADD CONSTRAINT report_status_history_pkey PRIMARY KEY (id);


--
-- Name: reports reports_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT reports_pkey PRIMARY KEY (id);


--
-- Name: residents residents_email_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.residents
    ADD CONSTRAINT residents_email_unique UNIQUE (email);


--
-- Name: residents residents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.residents
    ADD CONSTRAINT residents_pkey PRIMARY KEY (id);


--
-- Name: schedule_issues schedule_issues_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_issues
    ADD CONSTRAINT schedule_issues_pkey PRIMARY KEY (id);


--
-- Name: schedules schedules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedules
    ADD CONSTRAINT schedules_pkey PRIMARY KEY (id);


--
-- Name: system_admins system_admins_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.system_admins
    ADD CONSTRAINT system_admins_email_key UNIQUE (email);


--
-- Name: system_admins system_admins_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.system_admins
    ADD CONSTRAINT system_admins_pkey PRIMARY KEY (id);


--
-- Name: system_admins system_admins_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.system_admins
    ADD CONSTRAINT system_admins_username_key UNIQUE (username);


--
-- Name: idx_feedback_submitter; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_feedback_submitter ON public.feedback USING btree (submitter_role, submitter_id);


--
-- Name: idx_notifications_recipient; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_recipient ON public.notifications USING btree (recipient_role, recipient_id);


--
-- Name: idx_operational_reports_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_operational_reports_created_at ON public.operational_reports USING btree (created_at DESC);


--
-- Name: idx_operational_reports_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_operational_reports_type ON public.operational_reports USING btree (report_type);


--
-- Name: backup_logs backup_logs_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.backup_logs
    ADD CONSTRAINT backup_logs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.system_admins(id);


--
-- Name: collectors collectors_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collectors
    ADD CONSTRAINT collectors_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.municipal_admins(id);


--
-- Name: reports fk_reports_resident; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT fk_reports_resident FOREIGN KEY (resident_id) REFERENCES public.residents(id) ON DELETE CASCADE;


--
-- Name: notifications notifications_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.municipal_admins(id);


--
-- Name: on_demand_requests on_demand_requests_business_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.on_demand_requests
    ADD CONSTRAINT on_demand_requests_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.business_owners(business_id) ON DELETE CASCADE;


--
-- Name: on_demand_requests on_demand_requests_collector_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.on_demand_requests
    ADD CONSTRAINT on_demand_requests_collector_id_fkey FOREIGN KEY (collector_id) REFERENCES public.collectors(id);


--
-- Name: on_demand_requests on_demand_requests_reviewed_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.on_demand_requests
    ADD CONSTRAINT on_demand_requests_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.municipal_admins(id);


--
-- Name: operational_reports operational_reports_generated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.operational_reports
    ADD CONSTRAINT operational_reports_generated_by_fkey FOREIGN KEY (generated_by) REFERENCES public.municipal_admins(id);


--
-- Name: report_status_history report_status_history_changed_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report_status_history
    ADD CONSTRAINT report_status_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.municipal_admins(id);


--
-- Name: report_status_history report_status_history_report_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report_status_history
    ADD CONSTRAINT report_status_history_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.reports(id) ON DELETE CASCADE;


--
-- Name: schedule_issues schedule_issues_resident_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_issues
    ADD CONSTRAINT schedule_issues_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(id) ON DELETE CASCADE;


--
-- Name: schedule_issues schedule_issues_schedule_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_issues
    ADD CONSTRAINT schedule_issues_schedule_id_fkey FOREIGN KEY (schedule_id) REFERENCES public.schedules(id) ON DELETE CASCADE;


--
-- Name: schedules schedules_collector_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedules
    ADD CONSTRAINT schedules_collector_id_fkey FOREIGN KEY (collector_id) REFERENCES public.collectors(id);


--
-- Name: schedules schedules_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedules
    ADD CONSTRAINT schedules_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.municipal_admins(id);


--
-- PostgreSQL database dump complete
--

\unrestrict TbQWBHKTN30elsDU4gXZO1Ceam8jBpn7obe85otpSOpKlpnOWoqn4ezwfDKCKAA

