-- Migration 001: align restored backup with current backend code.
-- Safe: additive only. No DROP. No DELETE.

BEGIN;

ALTER TABLE public.residents
    ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true;

CREATE TABLE IF NOT EXISTS public.report_status_history (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id integer NOT NULL REFERENCES public.reports(id) ON DELETE CASCADE,
    old_status character varying(20) NOT NULL,
    new_status character varying(20) NOT NULL,
    changed_by integer NOT NULL REFERENCES public.municipal_admins(id),
    changed_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.schedules (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kifle_ketema character varying(100) NOT NULL,
    kebele character varying(100) NOT NULL,
    sefer character varying(100) NOT NULL,
    collection_day character varying(20) NOT NULL,
    collection_time time NOT NULL,
    notes text,
    created_by integer NOT NULL REFERENCES public.municipal_admins(id),
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMIT;
