-- Migration 002: business_owners table (UC-06)
-- Safe: additive only.

BEGIN;

CREATE TABLE IF NOT EXISTS public.business_owners (
    business_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_name character varying(100) NOT NULL,
    owner_name character varying(100) NOT NULL,
    phone_number character varying(15) NOT NULL UNIQUE,
    email character varying(100) UNIQUE,
    password_hash character varying(255) NOT NULL,
    address character varying(150) NOT NULL,
    business_type character varying(100) NOT NULL,
    kebele character varying(50) NOT NULL,
    kifle_ketema character varying(100) NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMIT;
