-- Migration 003: on_demand_requests table (UC-07, UC-08)
-- Safe: additive only.

BEGIN;

CREATE TABLE IF NOT EXISTS public.on_demand_requests (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id integer NOT NULL REFERENCES public.business_owners(business_id) ON DELETE CASCADE,
    latitude numeric(10, 8) NOT NULL,
    longitude numeric(11, 8) NOT NULL,
    description text,
    status character varying(20) NOT NULL DEFAULT 'pending',
    admin_notes text,
    reviewed_by integer REFERENCES public.municipal_admins(id),
    reviewed_at timestamp without time zone,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMIT;
