-- Migration 004: collectors table + assignment fields (UC-10, UC-11)
-- Safe: additive only.

BEGIN;

CREATE TABLE IF NOT EXISTS public.collectors (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name character varying(100) NOT NULL,
    phone_number character varying(15) NOT NULL UNIQUE,
    email character varying(255) NOT NULL UNIQUE,
    password_hash character varying(255) NOT NULL,
    kifle_ketema character varying(100) NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_by integer REFERENCES public.municipal_admins(id),
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE public.schedules
    ADD COLUMN IF NOT EXISTS collector_id integer REFERENCES public.collectors(id),
    ADD COLUMN IF NOT EXISTS collection_status character varying(20) NOT NULL DEFAULT 'scheduled';

ALTER TABLE public.on_demand_requests
    ADD COLUMN IF NOT EXISTS collector_id integer REFERENCES public.collectors(id),
    ADD COLUMN IF NOT EXISTS collection_status character varying(20) DEFAULT 'unassigned',
    ADD COLUMN IF NOT EXISTS assigned_at timestamp without time zone,
    ADD COLUMN IF NOT EXISTS completed_at timestamp without time zone,
    ADD COLUMN IF NOT EXISTS collector_notes text;

COMMIT;
