-- Migration 006: notifications table (UC-13)
-- Safe: additive only.

BEGIN;

CREATE TABLE IF NOT EXISTS public.notifications (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_role character varying(30) NOT NULL,
    recipient_id integer NOT NULL,
    title character varying(200) NOT NULL,
    message text NOT NULL,
    type character varying(50) NOT NULL,
    is_read boolean NOT NULL DEFAULT false,
    created_by integer REFERENCES public.municipal_admins(id),
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_notifications_recipient
    ON public.notifications(recipient_role, recipient_id);

COMMIT;
