-- Migration 007: feedback table (UC-14)
-- Safe: additive only.

BEGIN;

CREATE TABLE IF NOT EXISTS public.feedback (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submitter_role character varying(30) NOT NULL,
    submitter_id integer NOT NULL,
    rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment text,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_feedback_submitter
    ON public.feedback(submitter_role, submitter_id);

COMMIT;
