-- Migration 010: operational reports table (UC-15)
-- Separate from resident complaint reports.

BEGIN;

CREATE TABLE IF NOT EXISTS public.operational_reports (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_type character varying(30) NOT NULL,
    title character varying(200) NOT NULL,
    date_from date,
    date_to date,
    kifle_ketema character varying(100),
    report_data jsonb NOT NULL,
    generated_by integer NOT NULL REFERENCES public.municipal_admins(id),
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_operational_reports_type
    ON public.operational_reports (report_type);

CREATE INDEX IF NOT EXISTS idx_operational_reports_created_at
    ON public.operational_reports (created_at DESC);

COMMIT;
