-- Migration 011: system administrators + backup logs (UC-16)
-- Safe: additive only.

BEGIN;

CREATE TABLE IF NOT EXISTS public.system_admins (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username character varying(100) NOT NULL UNIQUE,
    email character varying(100) NOT NULL UNIQUE,
    password character varying(255) NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.backup_logs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename character varying(255) NOT NULL,
    file_path character varying(500) NOT NULL,
    size_bytes bigint,
    created_by integer REFERENCES public.system_admins(id),
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMIT;
