-- Migration 012: unified admin activity log audit trail
-- Safe: additive only. No DROP. No DELETE.

BEGIN;

CREATE TABLE IF NOT EXISTS public.activity_logs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_role varchar(30) NOT NULL,
    actor_id integer NOT NULL,
    actor_name varchar(255),
    action varchar(100) NOT NULL,
    entity_type varchar(50),
    entity_id integer,
    details jsonb,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_activity_logs_actor ON public.activity_logs (actor_role, actor_id);
CREATE INDEX IF NOT EXISTS idx_activity_logs_action ON public.activity_logs (action);
CREATE INDEX IF NOT EXISTS idx_activity_logs_created_at ON public.activity_logs (created_at);

COMMIT;