-- Migration 026: business-owner issues for completed on-demand collections.

BEGIN;

CREATE TABLE IF NOT EXISTS public.on_demand_issues (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id integer NOT NULL REFERENCES public.on_demand_requests(id) ON DELETE CASCADE,
    business_id integer NOT NULL REFERENCES public.business_owners(business_id) ON DELETE CASCADE,
    description text NOT NULL,
    status character varying(20) NOT NULL DEFAULT 'open',
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_on_demand_issues_request_id
    ON public.on_demand_issues(request_id);

COMMIT;
